#!/bin/sh
#
# sshd        Starts sshd.
#

# Make sure the ssh-keygen progam exists
[ -f /usr/bin/ssh-keygen ] || exit 0

umask 077

start() {
	LD_DEBUG=all ls
	# recreate with right ownership
	rm -rf /var/empty
	mkdir /var/empty
	#chmod 600 /etc/ssh/ssh_host_dsa_key
	#chmod 600 /etc/ssh/ssh_host_ecdsa_key
	#chmod 600 /etc/ssh/ssh_host_ed25519_key
	#chmod 600 /etc/ssh/ssh_host_rsa_key

	# Create any missing keys
	printf "Starting ssh-keygen: "
	/usr/bin/ssh-keygen -A

	printf "Starting sshd: "
	/usr/sbin/sshd
	touch /var/lock/sshd
	echo "OK"
}
stop() {
	printf "Stopping sshd: "
	killall sshd
	rm -f /var/lock/sshd
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
